### ISSUE TITLE
Training script

### ISSUE THREAD

**Issue by omeruth** [bvanaken/clinical-assertion-data#3]
Could you provide script for training the model?
Thanks

**Comment by Varun-Epi** [comment]
Please, can you provide the training script?
Thanks

**Comment by bvanaken** [comment]
Hello, thanks for your interest in our work.
I have uploaded the training files and a README here: https://drive.google.com/file/d/1zGy84nCuPAfkw91ib9GhCKmuZjvBdVgy/view?usp=sharing
Please note, that we have used FARM (https://github.com/deepset-ai/FARM) for training the model. Since the original FARM repo is no longer supported, I recommend training the model with another framework. I hope the code is still helpful for your experiments!

**Comment by omeruth** [comment]
Thank you for the help!

**Comment by Varun-Epi** [comment]
Thanks for the help!
